include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_specify_types: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_const_declarations: true
    unnecessary_this: true
    prefer_single_quotes: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    prefer_relative_imports: true
    avoid_classes_with_only_static_members: true

formatter:
  page_width: 300
